project_deepsleep/community/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path("1/", views.community_1, name= 'community_1'),
    path("1/<int:question_id>/", views.community_1_detail, name= 'community_1_detail'),
    path("1/question/create/", views.question_create_1, name = "question_create_1"),
    path("1/answer/create/<int:question_id>/", views.answer_create_1, name= 'answer_create_1'),
    path("1/question/modify/<int:question_id>/", views.question_modify_1, name= 'question_modify_1'),
    path("1/question/delete/<int:question_id>/", views.question_delete_1, name="question_delete_1"),

    path("2/", views.community_2, name= 'community_2'),
    path("2/<int:question_id>/", views.community_2_detail, name= 'community_2_detail'),
    path("2/question/create/", views.question_create_2, name = "question_create_2"),
    path("2/answer/create/<int:question_id>/", views.answer_create_2, name= 'answer_create_2'),
    path("2/question/modify/<int:question_id>/", views.question_modify_2, name= 'question_modify_2'),
    path("2/question/delete/<int:question_id>/", views.question_delete_2, name="question_delete_2"),

    path("3/", views.community_3, name= 'community_3'),
]

project_deepsleep/home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "home"

urlpatterns = [
    path("", views.home, name= 'home'),
    path("display_data/",views.display_data, name='display_data'),
    path("save_db/",views.save_csv_to_db, name='save_db')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_deepsleep/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("community/", include("community.urls")),
    path("account/", include("account.urls")),
    path("history/", include("history.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_deepsleep/community/models.py
from django.db import models
from account.models import User

class Question_1(models.Model):
    subject = models.CharField(max_length = 300)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank = True)
    def __str__(self):
        return self.subject

class Answer_1(models.Model):
    question = models.ForeignKey(Question_1, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateField()


class Question_2(models.Model):
    subject = models.CharField(max_length = 300)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank = True)

    def __str__(self):
        return self.subject

class Answer_2(models.Model):
    question = models.ForeignKey(Question_2, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateField()

project_deepsleep/community/forms.py
from django import forms
from community.models import Question_1, Question_2


class QuestionForm_1(forms.ModelForm):
    class Meta:
        model = Question_1
        fields = ['subject', 'content']
        widgets = {
            'subject':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control', 'rows':10}),
        }
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

class QuestionForm_2(forms.ModelForm):
    class Meta:
        model = Question_2
        fields = ['subject', 'content']
        widgets = {
            'subject':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control', 'rows':10}),
        }
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

project_deepsleep/community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question_1, Question_2
from django.utils import timezone
from .forms import QuestionForm_1, QuestionForm_2
import csv
from django.contrib.staticfiles import finders
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# 자유게시판
def community_1(request):
    question_list = Question_1.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, "community/community_1.html", context)

def community_1_detail(request, question_id):
    question = Question_1.objects.get(id = question_id)
    context = {"question" : question}
    return render(request, 'community/community_1_detail.html', context)

def answer_create_1(request, question_id):
    question = get_object_or_404(Question_1, pk = question_id)
    question.answer_1_set.create(content=request.POST.get('content'),
                               create_date=timezone.now())    
    return redirect("community:community_1_detail", question_id = question.id)

def question_create_1(request):
    if request.method == "POST":
        form = QuestionForm_1(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('community:community_1')
    else:
        form = QuestionForm_1()
    return render(request, 'community/question_form.html', {'form' : form })

@login_required(login_url = "account:login_user")
def question_modify_1(request, question_id):
    question = get_object_or_404(Question_1, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("community:community_1_detail", question_id = question.id)
    
    if request.method == "POST":
        form = QuestionForm_1(request.POST, instance = question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('community:community_1_detail', question_id = question.id)
    else:
        form = QuestionForm_1(instance=question)
    context = {"form" : form}
    return render(request, 'community/question_form.html', context)

def question_delete_1(request, question_id):
    question = get_object_or_404(Question_1, pk=question_id)
    if request.user != question.author:
        messages.error(request, "삭제권한이 없습니다")
        return redirect('community:community_1_detail', question_id = question.id)
    question.delete()
    return redirect("community:community_1")


# 질문게시판
@login_required(login_url = "account:login_user")
def community_2(request):
    question_list = Question_2.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, "community/community_2.html", context)

def community_2_detail(request, question_id):
    question = Question_2.objects.get(id = question_id)
    context = {"question" : question}
    return render(request, 'community/community_2_detail.html', context)

def answer_create_2(request, question_id):
    question = get_object_or_404(Question_2, pk = question_id)
    question.answer_2_set.create(content=request.POST.get('content'),
                               create_date=timezone.now())
    return redirect("community:community_2_detail", question_id = question.id)

def question_create_2(request):
    if request.method == "POST":
        form = QuestionForm_2(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('community:community_2')
    else:
        form = QuestionForm_1()
    return render(request, 'community/question_form.html', {'form' : form })


@login_required(login_url = "account:login_user")
def question_modify_2(request, question_id):
    question = get_object_or_404(Question_2, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("community:community_2_detail", question_id = question.id)
    
    if request.method == "POST":
        form = QuestionForm_2(request.POST, instance = question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('community:community_2_detail', question_id = question.id)
    else:
        form = QuestionForm_2(instance=question)
    context = {"form" : form}
    return render(request, 'community/question_form.html', context)

def question_delete_2(request, question_id):
    question = get_object_or_404(Question_2, pk=question_id)
    if request.user != question.author:
        messages.error(request, "삭제권한이 없습니다")
        return redirect('community:community_2_detail', question_id = question.id)
    question.delete()
    return redirect("community:community_2")

# 수면 저널

def community_3(request):
    csv_path = finders.find('csv/sciencedirect_Volume66.csv')
    
    csv_data = []

    #DB 넣는 코드 작성

    if csv_path:
        with open(csv_path, 'r', encoding='utf-8') as csv_file:
            csv_reader = csv.reader(csv_file)
            csv_data = list(csv_reader)
            
            for data in csv_data:
                print(data)

    csv_path = finders.find('csv/sciencedirect_Volume70.csv')

    csv_data2 = []

    if csv_path:
     with open(csv_path, 'r', encoding='utf-8') as csv_file:
        csv_reader = csv.reader(csv_file)
        csv_data = list(csv_reader)
            
        for data in csv_data:
            print(data)


    return render(request, "community/community_3.html", {'csv_data': csv_data})

project_deepsleep/templates/community/community_1.html
{% extends 'base.html' %}

{% block title%}  😶‍🌫️자유게시판 {% endblock %}

{% block content %}
{% if question_list%}
<h1 class="community_1">&nbsp;&nbsp;<i class="fa-solid fa-pencil fa-fade"></i>&nbsp;&nbsp;자유게시판</h1>
<div class = "container my-3 ">
    <table class="table caption-top">
        <caption>List of users</caption>
        <thead>
            <tr class="text-center" thead-dark>
                <th scope="col">NUM</th>
                <th scope="col" style = "width:50%">제목</th>
                <th scope="col">작성자</th>
                <th scope="col">작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% for question in question_list %}
                <tr class ="text-center">
                    <td>{{ forloop.counter }}</td>
                    <td class = "text-left"><a href="{% url 'community:community_1_detail' question.id %}">{{ question.subject}}</a></td>
                    <td>{{question.author.nickname}}</td>
                    <td> {{ question.create_date }}</td>
                </tr>
            {% endfor %}
  {% else %}
    <p>질문이 없습니다.</p>
{% endif %}
    </table>
    <a href="{% url 'community:question_create_1' %}" class ="btn btn-secondary">
        질문 등록
    </a>
</div>
{% endblock %}

project_deepsleep/templates/community/community_1_detail.html
{% extends 'base.html' %}

{% block title%} {{ question.subject }} {% endblock %}
{% block content %}
<div class="question_head">
<h1>{{ question.subject }}</h1>
<div>
<hr>

    {{question.content}}
    <br><br><br>
    {% if request.user == question.author %}
    <div class = "my-3">
        <a href="{% url 'community:question_modify_1' question.id%}"
        class = "btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class = "delete btn btn-sm btn-outline-secondary"
        data-url = "{% url 'community:question_delete_1' question.id %}">삭제</a>
    </div>
    {% endif %}

</div>
<hr>

<h5>{{question.answer_1_set.count}}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_1_set.all %}
            <li>{{answer.content}}</li>
        {% endfor %}
    </ul>
</div>
<form action="{% url 'community:answer_create_1' question.id%}" method="POST">
    {% csrf_token %}
    <textarea name="content" id="content" rows="1" style = "width:500px"></textarea>
    <br>
    <input type="submit" value = "답변등록">
</form>

{% endblock %}
{% block script %}
<script type = "text/javascript">
  $(document).ready(function(){
    $(".delete").on("click", function(){
      if(confirm("정말로 삭제하시겠습니까?")){
        location.href = $(this).data('uri');
      }
    });
  });
</script>
{% endblock %}

project_deepsleep/templates/community/community_2.html
{% extends 'base.html' %}

{% block title%} 🤔질문게시판 {% endblock %}

{% block content %}
<h1 class="community_2">&nbsp;&nbsp;<i class="fa-solid fa-bell fa-fade"></i>&nbsp;&nbsp;질문게시판</h1>

{% if question_list%}
<div class = "container my-3">
    <table class="table caption-top">
        <caption>List of users</caption>
        <thead>
            <tr class="text-center" thead-dark>
                <th scope="col">NUM</th>
                <th scope="col" style = "width:50%">제목</th>
                <th scope="col">작성자</th>
                <th scope="col">작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% for question in question_list %}
                <tr class ="text-center">
                    <td>{{ forloop.counter }}</td>
                    <td class = "text-left"><a href="{% url 'community:community_2_detail' question.id %}">{{ question.subject}}</a></td>
                    <td>{{question.author.nickname}}</td>
                    <td> {{ question.create_date }}</td>
                </tr>
            {% endfor %}
  {% else %}
    <p>질문이 없습니다.</p>
{% endif %}
    </table>
    <a href="{% url 'community:question_create_2' %}" class ="btn btn-secondary">
        질문 등록
    </a>
</div>
{% endblock %}

project_deepsleep/templates/community/community_2_detail.html
{% extends 'base.html' %}

{% block title%} {{ question.subject }} {% endblock %}
{% block content %}
<div class="question_head">
<h1>{{ question.subject }}</h1>
<div>
<hr>

{{question.content}}
<br><br><br>
{% if request.user == question.author %}
<div class = "my-3">
    <a href="{% url 'community:question_modify_2' question.id%}"
    class = "btn btn-sm btn-outline-secondary">수정</a>
    <a href="#" class = "delete btn btn-sm btn-outline-secondary"
    data-url = "{% url 'community:question_delete_2' question.id %}">삭제</a>
</div>
{% endif %}
</div>
<hr>

<h5>{{question.answer_2_set.count}}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_2_set.all %}
            <li>{{answer.content}}</li>
        {% endfor %}
    </ul>
</div>
<form action="{% url 'community:answer_create_2' question.id%}" method="POST">
    {% csrf_token %}
    <textarea name="content" id="content" rows="1" style = "width:500px"></textarea>
    <br>
    <input type="submit" value = "답변등록">
</form>

{% endblock %}

{% block script %}
<script type = "text/javascript">
  $(document).ready(function(){
    $(".delete").on("click", function(){
      if(confirm("정말로 삭제하시겠습니까?")){
        location.href = $(this).data('uri');
      }
    });
  });
</script>
{% endblock %}

project_deepsleep/templates/community/community_3.html
{% extends 'base.html' %}

{% load static %}

{% block title%}📕수면 저널 {% endblock %}

{% block content %}
<script src="{% static 'js/community_3.js' %}"></script>

<div class="row">
  <div class="col-4">
    <div id="list-example" class="list-group">
      {% for row in csv_data %}
        <a class="list-group-item list-group-item-action" href="#quote{{ forloop.counter }}">{{ row.0 }}</a>
      {% endfor %}
    </div>
  </div>
  <div class="col-8">
    <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-offset="0" class="scrollspy-example" tabindex="0">
      {% for row in csv_data %}
        <div class="card" id="quote{{ forloop.counter }}">
          <div class="card-header">
            <h2>{{ row.0 }}</h2>
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>{{ row.1|slice:":300" }}</p>
              <span class="dots">...</span>
              <span class="more" style="display: none;">{{ row.1|slice:"300:" }}{{ row.2 }}</span>
              <button onclick="readMore('quote{{ forloop.counter }}')" class="myBtn">Read more</button>
            </blockquote>
          </div>
        </div><br>
      {% endfor %}
    </div>
  </div>
</div> 

{% endblock  %}

project_deepsleep/templates/community/question_form.html
{% extends 'base.html' %}

<!-- 질문게시판 - 질문 등록 페이지-->

{% block content %}
<form method="POST" class="post-form my-3 question_head">
    <h3 class = "my-3 border-bottom pb-2">질문 등록</h3>
    <hr>
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit" class = "btn btn-secondary">저장하기</button>
</form>
{% endblock %}