project_deepsleep/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path("login/", views.login_user, name = "login"),
    path("logout/", views.logout_user, name = "logout"),
    path("register/", views.register_user, name = "register"),
]

project_deepsleep/community/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path("1/", views.community_1, name= 'community_1'),
    path("1/<int:question_id>/", views.community_1_detail, name= 'community_1_detail'),
    path("1/question/create/", views.question_create_1, name = "question_create_1"),
    path("1/answer/create/<int:question_id>/", views.answer_create_1, name= 'answer_create_1'),
    path("1/question/modify/<int:question_id>/", views.question_modify_1, name= 'question_modify_1'),
    path("1/question/delete/<int:question_id>/", views.question_delete_1, name="question_delete_1"),

    path("2/", views.community_2, name= 'community_2'),
    path("2/<int:question_id>/", views.community_2_detail, name= 'community_2_detail'),
    path("2/question/create/", views.question_create_2, name = "question_create_2"),
    path("2/answer/create/<int:question_id>/", views.answer_create_2, name= 'answer_create_2'),
    path("2/question/modify/<int:question_id>/", views.question_modify_2, name= 'question_modify_2'),
    path("2/question/delete/<int:question_id>/", views.question_delete_2, name="question_delete_2"),

    path("3/", views.community_3, name= 'community_3'),
]

project_deepsleep/history/urls.py
from django.urls import path
from . import views

app_name = "history"

urlpatterns = [
    path("", views.history, name= 'history'),
    path("<history_id>/", views.delete_history, name = "delete_history"),

]

project_deepsleep/home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "home"

urlpatterns = [
    path("", views.home, name= 'home'),
    path("display_data/",views.display_data, name='display_data'),
    path("save_db/",views.save_csv_to_db, name='save_db')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_deepsleep/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("community/", include("community.urls")),
    path("account/", include("account.urls")),
    path("history/", include("history.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_deepsleep/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} deep sleep {% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/history.css' %}">
    <link rel="stylesheet" href="{% static '/css/community_3.css' %}">
    <link rel="stylesheet" href="{% static '/css/community_2_detail.css' %}">
    <link rel="stylesheet" href="{% static '/css/question.css' %}">
    <link rel="stylesheet" href="{% static '/css/community_2.css' %}">
    <link rel="stylesheet" href="{% static '/css/community_1.css' %}">
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/login_page.css' %}">
    <link href="https://fonts.cdnfonts.com/css/sleeping" rel="stylesheet">
    <script src="% static 'code.jquery.com_jquery-3.7.1.min' %"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/92606c03d2.js" crossorigin="anonymous"></script>
    
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class = "container">
    {% if messages %}
      {% for message in  messages %}
        <div class="alert alert-dark alert-dismissible fade show" role="alert">
          {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
      
    <br>  
    {% if user.is_authenticated%}

    {% block content %}
    {% endblock  %}

    {% else %} 
    <!-- 로그인 화면 -->
    <div class="col-md-6 offset-md-3" id="login_page">
      <h1 class="heading_login">Login</h1>
      <br/>
      <form method="POST" action="{% url 'account:login' %}">
         {% csrf_token %}
         <div class="form-group">
            <input type="text" class="form-control" placeholder="Enter Username" name="username" id="input_username">
            <br/>
         </div>
         <div class="form-group">
            <input type="password" class="form-control" placeholder="Enter Password" name="password" id="input_pwd">
         </div>
         <br/>
   
         <button type="submit" class="btn btn-secondary" id="login_button">Login</button>
      </form>
    </div>
  
    {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
  
  </body>
</html>

project_deepsleep/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="{% url "home:home"%}">Deepsleep</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="collapsibleNavbar">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url "home:home"%}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              COMMUNITY
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url "community:community_1"%}">😶‍🌫️자유게시판</a></li>
              <li><a class="dropdown-item" href="{% url "community:community_2"%}">🤔질문게시판</a></li>
              <li><a class="dropdown-item" href="{% url "community:community_3"%}">💤수면 뉴스</a></li>
            </ul>
          </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link">Hi,{{user}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "history:history" %}">history</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "account:logout" %}">logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url "account:register"%}">register</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url "account:login"%}">login</a>
          </li>
        {% endif%}
      </ul>
  </div>
  </div>
</nav>